### ISSUE TITLE
raspberry pi docker failing to start TypeError: Cannot read property 'length' of undefined 

### ISSUE THREAD

**Issue by sfalvey** [fison67/TY-Connector#3]
Ty-connector in the raspberry pi docker image is failing to start and looping with the following in the log file. I have tried blowing away and re-installing with no luck,

> ty-connector@0.0.1 start /usr/src/app
> node ./bin/www

2019-04-28 08:40:02 [info]: WebSocket init
/usr/src/app/service/tuya.js:22
    for(var i=0; i<list.length; i++){
                        ^

TypeError: Cannot read property 'length' of undefined
    at TuyaService._init (/usr/src/app/service/tuya.js:22:25)
    at Timeout.TuyaService.setTimeout [as _onTimeout] (/usr/src/app/service/tuya.js:16:12)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ty-connector@0.0.1 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ty-connector@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

pi@magicmirror:~ $ docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:58:36 2017
 OS/Arch:      linux/arm

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:52:15 2017
 OS/Arch:      linux/arm
 Experimental: false
pi@magicmirror:~ $ docker  images
REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
fison67/ty-connector-rasp   0.0.1               60faa000f1ae        2 months ago        520MB

pi@magicmirror:~ $ docker container ls                        
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS              PORTS               NAMES
68ac2d39c6ce        fison67/ty-connector-rasp:0.0.1   "/usr/bin/entry.sh..."   19 minutes ago      Up 15 seconds                           ty-connector-rasp

**Comment by fison67** [comment]
Delete a ty-config.json & Restart a docker container

**Comment by sfalvey** [comment]
Its got further after removing the ty-config.json. The container is not looping now but the node startup is. From the container log...

> ty-connector@0.0.1 start /usr/src/app
> node ./bin/www

2019-04-29 02:34:10 [info]: WebSocket init

> ty-connector@0.0.1 start /usr/src/app
> node ./bin/www

2019-04-29 02:34:30 [info]: WebSocket init

> ty-connector@0.0.1 start /usr/src/app
> node ./bin/www

2019-04-29 02:34:51 [info]: WebSocket init

**Comment by fison67** [comment]
The service starts before config loads, causing a problem..

If you can go in to the docker container

apt-get install nano
nano /usr/src/app/service/tuya.js

find this part
-----------------------
setTimeout(()=>{
      this._init();
    }, 1000);
-----------------------
Modify to 5000.

This problem is occured

**Comment by sfalvey** [comment]
Thanks - that has resolved it for me.
